ghdata/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^test/$', views.test, name='test'),
    url(r'^profile/$', views.profile, name='profile'),
]

githubdata/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from ghdata import views

urlpatterns = [
    url(r'^$', views.profile, name='index'),
    url(r'^ghdata/', include('ghdata.urls', namespace='ghdata')),
    url(r'^admin/', admin.site.urls),
]

ghdata/models.py
from django.db import models

# Create your models here.

ghdata/views.py
import json
import requests
from django.contrib import messages
from django.shortcuts import render, HttpResponse


# Create your views here.


def index(request):
    return HttpResponse('Hello World!')


def test(request):
    return HttpResponse('My second view, the Test!')


def profile(request):
    parsed_data = []

    if request.method == 'POST':
        username = request.POST.get('user')
        req = requests.get('https://api.github.com/users/' + username)
        user_data = {}
        if req.status_code == 404:
            messages.info(request, 'Sorry, username not found')
        else:
            json_list = []
            json_list.append(json.loads(req.content))
            # user_data = {}

            for data in json_list:
                user_data['name'] = data['name']
                user_data['blog'] = data['blog']
                user_data['email'] = data['email']
                user_data['public_gists'] = data['public_gists']
                user_data['public_repos'] = data['public_repos']
                user_data['avatar_url'] = data['avatar_url']
                user_data['followers'] = data['followers']
                user_data['following'] = data['following']

        parsed_data.append(user_data)

    return render(request, 'ghdata/profile.html', {'data': parsed_data})

templates/ghdata/profile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href=" {% static "bootstrap/dist/css/bootstrap.min.css" %}">
	<link rel="stylesheet" type="text/css" href=" {% static "bootstrap/dist/css/bootstrap-theme.min.css" %}">

	<link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
	<title></title>
</head>
<body>

{% if messages %}
	<ul class="messages">
		{% for msg in messages %}

		<div class="alert alert-{{msg.level_tag}} alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
      			<span aria-hidden="true">&times;</span>
    		</button>
 			{{msg.message}}
		</div>

		{% endfor %}
	</ul>
{% endif %}


	<h1 class="text-center">Github User Data</h1>

	<div class="container">

		<div class="row">
			<div class="col-lg-12 text-center">
				<form class="form-signin" id="login-form" method="POST" action="{% url 'ghdata:profile' %}">

				{% csrf_token %}
				<br>
            	<input type="text" name="user" class="form-control" placeholder="Github User Name, e.g: DrkSephy" value="" required autofocus>
            	<br>
            	<button class="btn btn-lg btn-primary btn-block" type="submit">Get Data</button>


				</form>
			</div>
		</div>


		<div class="row">
			<div class="col-lg-12">


		<div class="table-responsive">

			<table class="table table-bordered table-hover table-striped tablesorter">
				<thead>
					<tr>
						<th class="header"> Username <i class="icon-sort"></i></th>
                  		<th class="header"> Blog <i class="icon-sort"></i></th>
                  		<th class="header"> Public Repos <i class="icon-sort"></i></th>
                  		<th class="header"> Public Gists <i class="icon-sort"></i></th>
                  		<th class="header"> Email <i class="icon-sort"></i></th>
                  		<th class="header"> Followers <i class="icon-sort"></i></th>
                  		<th class="header"> Following <i class="icon-sort"></i></th>
					</tr>
				</thead>

				<tbody>
					{% for key in data %}
						<tr>
							<td>{{ key.name }}</td>
                    		<td><a href="{{ key.blog }}" target="_blank">{{ key.blog }}</a></td>
                    		<td>{{ key.public_repos }}</td>
                    		<td>{{ key.public_gists }}</td>
                    		<td>{{ key.email }}</td>
                    		<td>{{ key.followers }}</td>
                    		<td>{{ key.following }}</td>
						</tr>
					{% endfor %}
				</tbody>

			</table>

		</div>


	</div>
		</div>
	</div>

	<script type="text/javascript" src="/static/jquery/dist/jquery.js"></script>
	<script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>